### ISSUE TITLE
Provide "SameSite" Cookies

### ISSUE THREAD

**Issue by adrienyhuel** [sanderfoobar/quart-session#3]
Quart provide SameSite cookie support in https://gitlab.com/pgjones/quart/-/issues/220

When you use set_cookie(...), can you provide the parameter "samesite" with the value from Quart config : 
self.get_cookie_samesite(app)

That way we can secure more the session, with "Strict" cookie.

**Comment by xmrdsc** [comment]
That's nice, thanks for bringing it to my attention.

Note for myself: https://gitlab.com/pgjones/quart/-/merge_requests/59

Will implement at a later date.

**Comment by filak** [comment]
See https://github.com/sferdi0/quart-session/pull/5

**Comment by sanderfoobar** [comment]
I'm assuming that solution works

**Comment by adrienyhuel** [comment]
@sanderfoobar yes it works, I tested it yesterday from git master.
